services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - internal_network

  oasisbridge:
    image: nazarovqurbonali/oasis-bridge:v17
    container_name: oasisbridge
    restart: always
    platform: linux/arm64
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/api/v1/ping"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - "3000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=5432;Database=oasis_bridge_db;User Id=postgres;Password=123456;
    depends_on:
      - postgres
    networks:
      - internal_network
  
  health-watcher:
    image: docker:cli
    container_name: health-watcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c '
      while true; do
        HEALTH_STATUS=$$(docker inspect --format="{{.State.Health.Status}}" oasisbridge 2>/dev/null)
        if [ "$$HEALTH_STATUS" = "unhealthy" ]; then
          echo "oasisbridge is unhealthy, restarting..."
          docker restart oasisbridge
        fi
        sleep 60
      done
      '
    depends_on:
      - oasisbridge
    networks:
      - internal_network

  oasisbridge_frontend:
    image: nazarovqurbonali/oasis-bridge-frontend:v12
    container_name: oasisbridge_frontend
    restart: always
    platform: linux/arm64
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://oasisbridge/api/v1
    depends_on:
      - oasisbridge
    networks:
      - internal_network

volumes:
  pgdata:

networks:
  internal_network:
