FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

WORKDIR /app
COPY / ./

RUN dotnet format /app/backend/src/api/API/API.csproj --verify-no-changes &&\
    dotnet publish /app/backend/src/api/API/API.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS runtime
WORKDIR /app

RUN apk -U upgrade &&\
    apk add --no-cache curl icu-libs &&\
    rm -rf /var/cache/apk/*
    
COPY --from=build /out ./
    
ENV ASPNETCORE_URLS=http://+:80

ENTRYPOINT ["dotnet", "API.dll"]