FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

WORKDIR /app
COPY . ./

RUN dotnet restore &&\
 dotnet publish backend/src/db-migrator/db-migrator.csproj -c Release -o /out --no-restore

FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine AS runtime

WORKDIR /app

COPY --from=build /out ./

ENTRYPOINT ["dotnet", "db-migrator.dll"]